### ISSUE TITLE
(Multiplayer Breaking) Null Reference Projectile Item causing massive log dumps

### ISSUE THREAD

**Issue by TaylorElliott** [MountainDrew8/Something#14]
Running through multiplayer server command prompt results in the log error below being spammed(thousands of lines a second) to the point the game is unplayable, players become unable to pick up items etc.

[1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
   at CalamityMod.CalamityMod.MidUpdateProjectileItem() in CalamityMod.cs:line 439
   at Terraria.ModLoader.ModHooks.MidUpdateProjectileItem()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)

**Comment by TaylorElliott** [comment]
Full mod list for reference in case it somehow matters:
```
  "BossCursor",
  "WeaponOut",
  "VeinMiner",
  "ShopExpander",
  "YABSSM",
  "NoMoreTombs",
  "RecipeBrowser",
  "MaxStackExtra",
  "MagicStorage",
  "ExtensibleInventory",
  "FasterPickaxes",
  "Census",
  "BossChecklist",
  "HamstarHelpers",
  "SmartDoors",
  "AutoTrash",
  "OmniSwing",
  "CalamityMod",
  "AlchemistNPCLite",
  "CalamityModMusic"
```

**Comment by TaylorElliott** [comment]
Updating, did some troubleshooting with the people in the discord and it's due to Malice mode in specific. Full writeup copied from discord.

Malice Multiplayer Lag Issue:
This only occurs on malice difficulty, multiplayer worlds.
[1/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
   at CalamityMod.CalamityMod.MidUpdateProjectileItem() in CalamityMod.cs:line 439
   at Terraria.ModLoader.ModHooks.MidUpdateProjectileItem()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)

This will spam the logs causing anything that needs to update per game tick lag and desync, sometimes causing the game to become unplayable for periods of time.
