### ISSUE TITLE
Crash on world generation

### ISSUE THREAD

**Issue by dankondr** [MountainDrew8/Something#48]
Game crashes on world generation:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalamityMod.World.MiscWorldgenRoutines.GenerateBiomeChests(GenerationProgress progress, GameConfiguration config) in CalamityMod\World\MiscWorldgenRoutines.cs:line 30
   at Terraria.GameContent.Generation.PassLegacy.ApplyPass(GenerationProgress progress, GameConfiguration configuration) in tModLoader\Terraria\GameContent\Generation\PassLegacy.cs:line 226
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12378
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2345
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2335
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[00:52:49.287] [.NET ThreadPool Worker/ERROR] [tML]: Произошла ошибка во время создания мира
CalamityDungeonBiomeChests
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalamityMod.World.MiscWorldgenRoutines.GenerateBiomeChests(GenerationProgress progress, GameConfiguration config) in CalamityMod\World\MiscWorldgenRoutines.cs:line 30
   at Terraria.GameContent.Generation.PassLegacy.ApplyPass(GenerationProgress progress, GameConfiguration configuration) in tModLoader\Terraria\GameContent\Generation\PassLegacy.cs:line 226
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30
[00:52:49.288] [.NET ThreadPool Worker/ERROR] [Terraria]: Произошла ошибка во время создания мира
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 60
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12378
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2345
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2335
[00:53:19.467] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs" 
```

Calamity version: 2.0.0.3
tModLauncher version: 2022.7.58.4

**Comment by SpeedNintendo** [comment]
Can confirm the same issue started occurring for me once I updated to tmodloader 2022.7.58.4.

It is 100% an issue introduced with the tmodloader update, but would need to get patched by calamity devs

**Comment by Akwinem** [comment]
I have the same problem, wanna play for the first time and this happens :/

**Comment by blackd** [comment]
same issue

**Comment by LargeShot1** [comment]
how long should we expect the calamity devs to react to this issue, 
will they update the mod soon?

**Comment by slimeball300** [comment]
this fixed it for me https://steamcommunity.com/sharedfiles/filedetails/?id=2844842520
